@startuml
'https://plantuml.com/class-diagram

class InventoryApp

class ErrorWindowController




class MenuController{
        //FXML CONTENT//


        public TableColumn ItemCol;

        public TableColumn SerialNumberCol;

        public TableColumn ValueCol;

        public TableView InformationTable;

        public Button SearchButton;

        public TextField ItemNameTextField;

        public TextField ItemSerialNumberTextField;

        public TextField ItemValueTextField;

        //BACKEND VARS//


     HashMap<InventoryItem> ItemHolder



     public void NewMenuButtonClicked(ActionEvent actionEvent)


     public void SaveInventoryButtonClicked(ActionEvent actionEvent)


     public void LoadInventoryButtonClicked(ActionEvent actionEvent)


     public void AddItemButtonClicked(ActionEvent actionEvent)


     public void DeleteItemButtonClicked(ActionEvent actionEvent)


     public void SearchButtonClicked(ActionEvent actionEvent)

}

class InventoryItem{
   private Double monetaryValue
   private String serialNum
   private String itemName

   Public InventoryItem(Double monetaryValue,String serialNum, String itemName)

   getItemName()
   setItemName(String newName)

   getSerialNum()
   setSerialNum(String newSerial)

   getMonetaryValue()
   setMonetaryValue(String newValue)

}

 class FileManager{
    private File filePath

    FileManager(String filePath)
    FileManager(File  filePath)


    public writeFile(String toWrite)

    public String readFile()

    getFile()

}

class LoadFile{

    LoadFile(String filePath)
    LoadFile(File filePath)





}

class SaveFile{


  SaveFile(String filePath,String fileName)
  SaveFile(File filePath,String fileName)




}


javafx.Application <|-- InventoryApp
LoadFile <|-- FileManager
SaveFile <|-- FileManager

InventoryApp --> MenuController


MenuController--> LoadFile
MenuController-->SaveFile

MenuController-InventoryItem
@enduml